name: Build docker images (scheduled)

on:
  push:
    branches:
      - test_enable_pytorch_nightly_ci
  repository_dispatch:
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: docker-images-builds
  cancel-in-progress: false

jobs:
#  latest-docker:
#    name: "Latest PyTorch + TensorFlow [dev]"
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Check out code
#        uses: actions/checkout@v2
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker/transformers-all-latest-gpu
#          build-args: |
#            REF=main
#          push: true
#          tags: huggingface/transformers-all-latest-gpu-test

  latest-with-torch-nightly-docker:
    name: "Nightly PyTorch + Stable TensorFlow"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/transformers-all-latest-gpu
          build-args: |
            REF=main
            PYTORCH=pre
          push: true
          tags: huggingface/transformers-all-latest-torch-nightly-gpu-test
#
#  latest-torch-deepspeed-docker:
#    name: "Latest PyTorch + DeepSpeed"
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Check out code
#        uses: actions/checkout@v2
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker/transformers-pytorch-deepspeed-latest-gpu
#          build-args: |
#            REF=main
#          push: true
#          tags: huggingface/transformers-pytorch-deepspeed-latest-gpu-test
#
#  nightly-torch-deepspeed-docker:
#    name: "Nightly PyTorch + DeepSpeed"
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Check out code
#        uses: actions/checkout@v2
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker/transformers-pytorch-deepspeed-nightly-gpu
#          build-args: |
#            REF=main
#          push: true
#          tags: huggingface/transformers-pytorch-deepspeed-nightly-gpu-test
